project:
  type: website
page-layout: full
website:
  title: "Mikael Moise"
  navbar:
    pinned: true
    right:
    - icon: envelope
      text: Email
      href: mailto:mikaelmoise00@gmail.com
    - icon: file-pdf
      text: Resume
    - icon: github
      text: GitHub
      href: https://github.com/arrismo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      body-width: 1100px

editor: visual

